# Generated by Django 4.2.23 on 2025-07-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmerData',
            new_name='FarmerInfo',
        ),
    ]
