# Generated by Django 4.2.23 on 2025-07-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_farmerdata_farmerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'farmers_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FarmerInfo',
        ),
    ]
