# Generated by Django 4.2.23 on 2025-08-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_farmersdata_delete_farmerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FarmersData',
        ),
    ]
