# Generated by Django 4.2.23 on 2025-08-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdata_delete_farmersdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='user_data',
        ),
    ]
